name: 'test'

on:
  workflow_dispatch:
  pull_request:

jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1

      - name: 'Setup terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.1.8'

      - name: 'Terragrunt init'
        run: terraform init

      - name: 'Terragrunt validate'
        run: terraform validate

# Reusable Workflow https://github.blog/2022-02-10-using-reusable-workflows-github-actions/ 
# Linting ...
# Kubernetes https://dev.to/kitarp29/running-kubernetes-on-github-actions-f2c
# Security https://medium.com/@nanditasahu031/how-to-use-different-tools-to-do-terraform-checks-in-github-actions-b16e9fa73c42
